name: Yarn Publish
on: push
# on:
#     push:
# paths:
#     - 'firstload/**'
# branches:
#     - master
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
            - name: Install main dependencies
              run: cd firstload && yarn install
            - name: Install other dependencies
              run: cd client && yarn install
            - name: Build Bundle
              run: cd firstload && yarn build
            - name: Publish
              if: github.ref == 'refs/heads/master'
              run: yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
