name: Yarn Publish
on:
    push:
        paths:
            - 'firstload/**'
        branches:
            - master
defaults:
    run:
        working-directory: firstload
jobs:
    publish:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: firstload
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
            - name: Install dependencies
              run: yarn install
            - name: pwd
              run: pwd
            - name: Build Bundle
              run: yarn build
            - name: Publish
              run: yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
